### PR TITLE
allow for only installing haproxy 1.5

### PR DESCRIPTION
**Pull request by jonhatalla**
- separated install and configure logic cleanly
- allow for only installing application by setting haproxy_use_config flag to false

As it stands, this PR will only change the folder structure.  We manage our own haproxy config with a specialized template, but everything else in your role is great for us.

### CODE REVIEW

**Comment by PierrePaul** [comment]
Good idea. Would you mind if I changed the var to "haproxy_manage_config" [True | False] ?

**Comment by jonhatalla** [comment]
not at all

**Comment by jonhatalla** [comment]
just a heads up - this won't start the service if `haproxy_manage_config` is set to false.  This actually should be expected since the default config won't be of much use anyways.

The current tests should still pass as no functionality has changed from their perspective.

**Comment by jonhatalla** [comment]
i went ahead and updated the variable name

**Comment by PierrePaul** [comment]
Thank you!

**Pull request merged**
